#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd $DIR/..
npm ci

clojure -A:shadow-cljs -A:test release node-test-simple &&
    node -r source-map-support/register target/node-test-simple/node-tests.js
